# Generated by Django 5.0.2 on 2024-03-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_remove_asistencia_confirmado2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='usuario',
            new_name='id_usuario',
        ),
    ]
