# Generated by Django 5.0.2 on 2024-03-25 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='school',
            name='password',
        ),
        migrations.AddField(
            model_name='school',
            name='sport',
            field=models.TextField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='school',
            name='mision',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='school',
            name='policy',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='school',
            name='vision',
            field=models.TextField(default='', max_length=500),
        ),
    ]
